name: intl_phone_field_improve
description: Test and learn for myself, Refer to intl_phone_field for practice.
version: 1.0.1
homepage: https://github.com/CKseraph/intl_phone_field_improve


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
